#ifndef ACTOR_TYPES_HEADER_INCLUDED
#define ACTOR_TYPES_HEADER_INCLUDED

enum ActorType
{
    ACTOR_TYPE_NONE,
    ACTOR_TYPE_VILLAIN,
    ACTOR_TYPE_DOOR,
    ACTOR_TYPE_PLAYER,
    ACTOR_TYPE_CONTAINER,
};

#endif